VEHICLE_RANGE_MILES = 500
MILES_PER_GALLON = 10
TANK_GALLONS = 50
START_TANK_GALLONS = 50      # full tank, per your decision
CORRIDOR_TOLERANCE_MILES = 20
ROUTE_SAMPLE_SPACING_MILES = 10
OSRM_BASE_URL = "https://router.project-osrm.org"
