# Generated by Django 5.2.16 on 2026-07-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('coord_source', models.CharField(blank=True, max_length=24)),
            ],
            options={
                'ordering': ['opis_id'],
            },
        ),
    ]
